<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xueliandan.gulimall</groupId>
    <artifactId>guli_mall</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>guli-mall</name>
    <description>guli-mall根工程</description>
    <packaging>pom</packaging>

    <modules>
        <module>guli-coupon</module>
        <module>guli-coupon-api</module>
        <module>guli-gateway</module>
        <module>guli-member</module>
        <module>guli-member-api</module>
        <module>guli-order</module>
        <module>guli-order-api</module>
        <module>guli-product</module>
        <module>guli-product-api</module>
        <module>guli-ware</module>
        <module>guli-ware-api</module>
        <module>guli-common</module>
        <module>renren-fast</module>
        <module>renren-generator</module>
        <module>guli-third-party</module>
        <module>guli-search</module>
        <module>guli-search-api</module>
    </modules>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.3.12.RELEASE</spring-boot.version>
        <spring-cloud.version>Hoxton.SR12</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>3.5.11</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 由于 spring-boot-dependencies:2.3.12.RELEASE 中管理了 elasticsearch 的版本
                          但是和本项目中 es 的版本不同, 本项目 es 版本 7.4.2。 并且根项目还不是通过 parent 标签继承的，
                          而是使用 import 进行管理的。因此这里要手动导入 gav，这样就优先使用指定的 elasticsearch 的版本了
                          使用 properties 改写的方式就不行了。-->
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>7.4.2</version>
            </dependency>
            <dependency>
                <groupId>org.elasticsearch.client</groupId>
                <artifactId>elasticsearch-rest-client</artifactId>
                <version>7.4.2</version>
            </dependency>


        </dependencies>
    </dependencyManagement>
</project>
